### ISSUE TITLE
是否支持网宿和UCloud的云服务

### ISSUE THREAD

**Issue by liutao6982** [AnyRTC/DyncRTMPLiveClient-IOS#1]
公司现在选方案，在网上找了很多方案都非常不靠谱，测试了下贵公司的方案，效果很好，也非常稳定，但是对于网宿和UCloud的云服务是否支持没有看到。

**Comment by BoYuanZjq** [comment]
你好，该库支持网宿和UCloud云服务的，市面上主流的云服务都支持的。请放心使用~
