### ISSUE TITLE
 Linker errors when trying to build

### ISSUE THREAD

**Issue by dmdque** [AnyRTC/DyncRTMPLiveClient-IOS#2]
Unfortunately I don't read or write Chinese, but I'm hoping we can get by with Google translate.

When building, I get the following errors:
![image](https://cloud.githubusercontent.com/assets/5205766/18690774/e4f956e2-7f5d-11e6-9c67-a58c50f5e847.png)

I've tried changing the Architecture Settings and made sure Enable Bitcode is set to No. I'm out of ideas about how to fix these.

Using Xcode 7.3.1.

**Comment by BoYuanZjq** [comment]
This project we have no maintenance，you can jump https://github.com/AnyRTC/RTMPCHybridEngine-IOS, This project is our promotion right now。
answer:
you need debug with phone,We didn't do simulator library，sorry~

**Comment by dmdque** [comment]
Ah, it worked when I used a physical device. 谢谢!
